name: Check manual dependencies

on:
  schedule:
    - cron: "25 3 * * 2" # weekly: tuesdays at 3:25
  workflow_dispatch: # Allow manual run

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check versions of manually managed dependencies
        run: |
          ./release/100-check-latest-versions.sh
