name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Version to build and release. (e.g. 1.2.3 or 1.2.4-dev)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          echo "input:  ${{ github.event.inputs.name }}"
          git fetch --tags
          source release/source.sh
          echo "VERSION: $VERSION"
          git tag "${{ github.event.inputs.name }}"
          echo "VERSION: $VERSION"
