name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Version to tag, build and release. (e.g. 1.2.3 or 1.2.4-dev)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        run: |
          sudo apt-get update
          sudo apt-get install -y golang wget
          wget -q https://github.com/goreleaser/goreleaser/releases/download/v1.7.0/goreleaser_1.7.0_amd64.deb
          sudo dpkg -i goreleaser*.deb
          rm -f *.deb
      - name: Set Version
        run: |
          echo "Input version: ${{ github.event.inputs.name }}"
          git fetch --tags origin
          git tag "v${{ github.event.inputs.name }}"
          source release/source.sh
      - name: Protoc
        run: |
          ./release/0-get-protoc-binaries.sh
      - name: Build Archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./release/1-build-go-archive.sh
      - name: DockerHub Release
        run: |
          ./release/2-release-docker-image.sh