name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Version to tag, build and release. (e.g. 1.2.3 or 1.2.4-dev)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        run: |
          sudo apt-get update
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
          sudo apt install -y golang goreleaser
      - name: Set Version
        run: |
          echo "Input version: ${{ github.event.inputs.name }}"
          git fetch --tags origin
          git tag "v${{ github.event.inputs.name }}"
          source release/source.sh
      - name: Protoc
        run: |
          ./release/0-get-protoc-binaries.sh
      - name: Build Archive
        run: |
          ./release/1-build-go-archive.sh
      - name: DockerHub Release
        run: |
          ./release/2-release-docker-image.sh